import { lazy as _lazy } from "react";

function lazy(importFn: Function) {
  return _lazy(async () => {
    const m = await importFn();
    return { default: m.ReactComponent };
  });
}

export const icons = {
  // Outline
  Add: lazy(async () => import("./assets/add.svg")),
  AddressBook: lazy(async () => import("./assets/address-book.svg")),
  AlarmClock: lazy(async () => import("./assets/alarm-clock.svg")),
  AlignCenter: lazy(async () => import("./assets/align-center.svg")),
  AlignJustify: lazy(async () => import("./assets/align-justify.svg")),
  AlignLeft: lazy(async () => import("./assets/align-left.svg")),
  AlignRight: lazy(async () => import("./assets/align-right.svg")),
  Ambulance: lazy(async () => import("./assets/ambulance.svg")),
  AngleDoubleLeft: lazy(async () => import("./assets/angle-double-left.svg")),
  AngleDoubleRight: lazy(async () => import("./assets/angle-double-right.svg")),
  AngleDoubleSmallLeft: lazy(
    async () => import("./assets/angle-double-small-left.svg")
  ),
  AngleDoubleSmallRight: lazy(
    async () => import("./assets/angle-double-small-right.svg")
  ),
  AngleDown: lazy(async () => import("./assets/angle-down.svg")),
  AngleLeft: lazy(async () => import("./assets/angle-left.svg")),
  AngleRight: lazy(async () => import("./assets/angle-right.svg")),
  AngleSmallDown: lazy(async () => import("./assets/angle-small-down.svg")),
  AngleSmallLeft: lazy(async () => import("./assets/angle-small-left.svg")),
  AngleSmallRight: lazy(async () => import("./assets/angle-small-right.svg")),
  AngleSmallUp: lazy(async () => import("./assets/angle-small-up.svg")),
  AngleUp: lazy(async () => import("./assets/angle-up.svg")),
  Apple: lazy(async () => import("./assets/apple.svg")),
  Apps: lazy(async () => import("./assets/apps.svg")),
  AppsAdd: lazy(async () => import("./assets/apps-add.svg")),
  AppsDelete: lazy(async () => import("./assets/apps-delete.svg")),
  AppsSort: lazy(async () => import("./assets/apps-sort.svg")),
  Archive: lazy(async () => import("./assets/archive.svg")),
  ArrowDown: lazy(async () => import("./assets/arrow-down.svg")),
  ArrowFromBottom: lazy(async () => import("./assets/arrow-from-bottom.svg")),
  ArrowLeft: lazy(async () => import("./assets/arrow-left.svg")),
  ArrowRight: lazy(async () => import("./assets/arrow-right.svg")),
  ArrowSmallDown: lazy(async () => import("./assets/arrow-small-down.svg")),
  ArrowSmallLeft: lazy(async () => import("./assets/arrow-small-left.svg")),
  ArrowSmallRight: lazy(async () => import("./assets/arrow-small-right.svg")),
  ArrowSmallUp: lazy(async () => import("./assets/arrow-small-up.svg")),
  ArrowUp: lazy(async () => import("./assets/arrow-up.svg")),
  Asterik: lazy(async () => import("./assets/asterik.svg")),
  At: lazy(async () => import("./assets/at.svg")),
  Badge: lazy(async () => import("./assets/badge.svg")),
  Balloons: lazy(async () => import("./assets/balloons.svg")),
  Ban: lazy(async () => import("./assets/ban.svg")),
  BandAid: lazy(async () => import("./assets/band-aid.svg")),
  Bank: lazy(async () => import("./assets/bank.svg")),
  Baseball: lazy(async () => import("./assets/baseball.svg")),
  Basketball: lazy(async () => import("./assets/basketball.svg")),
  Bed: lazy(async () => import("./assets/bed.svg")),
  Beer: lazy(async () => import("./assets/beer.svg")),
  Bell: lazy(async () => import("./assets/bell.svg")),
  BellRing: lazy(async () => import("./assets/bell-ring.svg")),
  Bike: lazy(async () => import("./assets/bike.svg")),
  Billiard: lazy(async () => import("./assets/billiard.svg")),
  Bold: lazy(async () => import("./assets/bold.svg")),
  Book: lazy(async () => import("./assets/book.svg")),
  BookAlt: lazy(async () => import("./assets/book-alt.svg")),
  Bookmark: lazy(async () => import("./assets/bookmark.svg")),
  Bowling: lazy(async () => import("./assets/bowling.svg")),
  Box: lazy(async () => import("./assets/box.svg")),
  BoxAlt: lazy(async () => import("./assets/box-alt.svg")),
  Briefcase: lazy(async () => import("./assets/briefcase.svg")),
  Broom: lazy(async () => import("./assets/broom.svg")),
  Brush: lazy(async () => import("./assets/brush.svg")),
  Building: lazy(async () => import("./assets/building.svg")),
  Bulb: lazy(async () => import("./assets/bulb.svg")),
  CallIncoming: lazy(async () => import("./assets/call-incoming.svg")),
  CaretDown: lazy(async () => import("./assets/caret-down.svg")),
  CaretLeft: lazy(async () => import("./assets/caret-left.svg")),
  CaretRight: lazy(async () => import("./assets/caret-right.svg")),
  CaretUp: lazy(async () => import("./assets/caret-up.svg")),
  Carrot: lazy(async () => import("./assets/carrot.svg")),
  ChartHistogram: lazy(async () => import("./assets/chart-histogram.svg")),
  ChartSetTheory: lazy(async () => import("./assets/chart-set-theory.svg")),
  ChartTree: lazy(async () => import("./assets/chart-tree.svg")),
  Check: lazy(async () => import("./assets/check.svg")),
  Checkbox: lazy(async () => import("./assets/checkbox.svg")),
  ChildHead: lazy(async () => import("./assets/child-head.svg")),
  Circle: lazy(async () => import("./assets/circle.svg")),
  Clip: lazy(async () => import("./assets/clip.svg")),
  Clock: lazy(async () => import("./assets/clock.svg")),
  Cloud: lazy(async () => import("./assets/cloud.svg")),
  Clouds: lazy(async () => import("./assets/clouds.svg")),
  Cocktail: lazy(async () => import("./assets/cocktail.svg")),
  Coffee: lazy(async () => import("./assets/coffee.svg")),
  Dollar: lazy(async () => import("./assets/dollar.svg")),
  Duplicate: lazy(async () => import("./assets/duplicate.svg")),
  Eye: lazy(async () => import("./assets/eye.svg")),
  Folder: lazy(async () => import("./assets/folder.svg")),
  Gift: lazy(async () => import("./assets/gift.svg")),
  Key: lazy(async () => import("./assets/key.svg")),
  Link: lazy(async () => import("./assets/link.svg")),
  Marker: lazy(async () => import("./assets/marker.svg")),
  MarkerTime: lazy(async () => import("./assets/marker-time.svg")),
  MenuBurger: lazy(async () => import("./assets/menu-burger.svg")),
  MenuDots: lazy(async () => import("./assets/menu-dots.svg")),
  Microphone: lazy(async () => import("./assets/microphone.svg")),
  MicrophoneAlt: lazy(async () => import("./assets/microphone-alt.svg")),
  Minus: lazy(async () => import("./assets/minus.svg")),
  MinusSmall: lazy(async () => import("./assets/minus-small.svg")),
  Money: lazy(async () => import("./assets/money.svg")),
  Moon: lazy(async () => import("./assets/moon.svg")),
  Mouse: lazy(async () => import("./assets/mouse.svg")),
  MugAlt: lazy(async () => import("./assets/mug-alt.svg")),
  Music: lazy(async () => import("./assets/music.svg")),
  Pencil: lazy(async () => import("./assets/pencil.svg")),
  Play: lazy(async () => import("./assets/play.svg")),
  Plus: lazy(async () => import("./assets/plus.svg")),
  Pound: lazy(async () => import("./assets/pound.svg")),
  Power: lazy(async () => import("./assets/power.svg")),
  Salad: lazy(async () => import("./assets/salad.svg")),
  Settings: lazy(async () => import("./assets/settings.svg")),
  SignIn: lazy(async () => import("./assets/sign-in.svg")),
  SignOut: lazy(async () => import("./assets/sign-out.svg")),
  Skateboard: lazy(async () => import("./assets/skateboard.svg")),
  Smile: lazy(async () => import("./assets/smile.svg")),
  Soap: lazy(async () => import("./assets/soap.svg")),
  Subtitles: lazy(async () => import("./assets/subtitles.svg")),
  Sun: lazy(async () => import("./assets/sun.svg")),
  Sunrise: lazy(async () => import("./assets/sunrise.svg")),
  Sword: lazy(async () => import("./assets/sword.svg")),
  Syringe: lazy(async () => import("./assets/syringe.svg")),
  Tablet: lazy(async () => import("./assets/tablet.svg")),
  Tennis: lazy(async () => import("./assets/tennis.svg")),
  Test: lazy(async () => import("./assets/test.svg")),
  TimeForward: lazy(async () => import("./assets/time-forward.svg")),
  Tornado: lazy(async () => import("./assets/tornado.svg")),
  Transform: lazy(async () => import("./assets/transform.svg")),
  Trash: lazy(async () => import("./assets/trash.svg")),
  Trophy: lazy(async () => import("./assets/trophy.svg")),
  Underline: lazy(async () => import("./assets/underline.svg")),
  Undo: lazy(async () => import("./assets/undo.svg")),
  User: lazy(async () => import("./assets/user.svg")),
  Yen: lazy(async () => import("./assets/yen.svg")),

  // Solids
  SolidCloud: lazy(async () => import("./assets/solid-cloud.svg")),
  SolidAmbulance: lazy(async () => import("./assets/solid-ambulance.svg")),
  SolidVolume: lazy(async () => import("./assets/solid-volume.svg")),
  SolidZoomIn: lazy(async () => import("./assets/solid-zoom-in.svg")),
  SolidZoomOut: lazy(async () => import("./assets/solid-zoom-out.svg")),
};
