import { lazy as _lazy } from "react";

function lazy(importFn: Function) {
  return _lazy(async () => {
    const m = await importFn();
    return { default: m.ReactComponent };
  });
}

export const icons = {
  Add: lazy(async () => import("./assets/add.svg")),
  AddressBook: lazy(async () => import("./assets/address-book.svg")),
  AddressBookSolid: lazy(async () => import("./assets/address-book-solid.svg")),
  AddSolid: lazy(async () => import("./assets/add-solid.svg")),
  AlarmClock: lazy(async () => import("./assets/alarm-clock.svg")),
  AlarmClockSolid: lazy(async () => import("./assets/alarm-clock-solid.svg")),
  AlignCenter: lazy(async () => import("./assets/align-center.svg")),
  AlignJustify: lazy(async () => import("./assets/align-justify.svg")),
  AlignLeft: lazy(async () => import("./assets/align-left.svg")),
  AlignRight: lazy(async () => import("./assets/align-right.svg")),
  Ambulance: lazy(async () => import("./assets/ambulance.svg")),
  AmbulanceSolid: lazy(async () => import("./assets/ambulance-solid.svg")),
  AngleDoubleLeft: lazy(async () => import("./assets/angle-double-left.svg")),
  AngleDoubleSmallLeft: lazy(
    async () => import("./assets/angle-double-small-left.svg")
  ),
  AngleDown: lazy(async () => import("./assets/angle-down.svg")),
  AngleSmallDown: lazy(async () => import("./assets/angle-small-down.svg")),
  Apple: lazy(async () => import("./assets/apple.svg")),
  AppleSolid: lazy(async () => import("./assets/apple-solid.svg")),
  Apps: lazy(async () => import("./assets/apps.svg")),
  AppsAdd: lazy(async () => import("./assets/apps-add.svg")),
  AppsAddSolid: lazy(async () => import("./assets/apps-add-solid.svg")),
  AppsDelete: lazy(async () => import("./assets/apps-delete.svg")),
  AppsDeleteSolid: lazy(async () => import("./assets/apps-delete-solid.svg")),
  AppsSolid: lazy(async () => import("./assets/apps-solid.svg")),
  AppsSort: lazy(async () => import("./assets/apps-sort.svg")),
  AppsSortSolid: lazy(async () => import("./assets/apps-sort-solid.svg")),
  Archive: lazy(async () => import("./assets/archive.svg")),
  ArchiveSolid: lazy(async () => import("./assets/archive-solid.svg")),
  ArrowDown: lazy(async () => import("./assets/arrow-down.svg")),
  ArrowFromBottom: lazy(async () => import("./assets/arrow-from-bottom.svg")),
  ArrowSmallDown: lazy(async () => import("./assets/arrow-small-down.svg")),
  Asterik: lazy(async () => import("./assets/asterik.svg")),
  AsterikSolid: lazy(async () => import("./assets/asterik-solid.svg")),
  At: lazy(async () => import("./assets/at.svg")),
  Badge: lazy(async () => import("./assets/badge.svg")),
  BadgeSolid: lazy(async () => import("./assets/badge-solid.svg")),
  Balloons: lazy(async () => import("./assets/balloons.svg")),
  BalloonsSolid: lazy(async () => import("./assets/balloons-solid.svg")),
  Ban: lazy(async () => import("./assets/ban.svg")),
  BandAid: lazy(async () => import("./assets/band-aid.svg")),
  BandAidSolid: lazy(async () => import("./assets/band-aid-solid.svg")),
  Bank: lazy(async () => import("./assets/bank.svg")),
  BankSolid: lazy(async () => import("./assets/bank-solid.svg")),
  BarberShop: lazy(async () => import("./assets/barber-shop.svg")),
  Baseball: lazy(async () => import("./assets/baseball.svg")),
  BaseballSolid: lazy(async () => import("./assets/baseball-solid.svg")),
  Basketball: lazy(async () => import("./assets/basketball.svg")),
  BasketballSolid: lazy(async () => import("./assets/basketball-solid.svg")),
  Bed: lazy(async () => import("./assets/bed.svg")),
  BedSolid: lazy(async () => import("./assets/bed-solid.svg")),
  Beer: lazy(async () => import("./assets/beer.svg")),
  BeerSolid: lazy(async () => import("./assets/beer-solid.svg")),
  Bell: lazy(async () => import("./assets/bell.svg")),
  BellRing: lazy(async () => import("./assets/bell-ring.svg")),
  BellRingSolid: lazy(async () => import("./assets/bell-ring-solid.svg")),
  BellSchool: lazy(async () => import("./assets/bell-school.svg")),
  BellSchoolSolid: lazy(async () => import("./assets/bell-school-solid.svg")),
  BellSolid: lazy(async () => import("./assets/bell-solid.svg")),
  Bike: lazy(async () => import("./assets/bike.svg")),
  BikeSolid: lazy(async () => import("./assets/bike-solid.svg")),
  Billiard: lazy(async () => import("./assets/billiard.svg")),
  BilliardSolid: lazy(async () => import("./assets/billiard-solid.svg")),
  Bold: lazy(async () => import("./assets/bold.svg")),
  Book: lazy(async () => import("./assets/book.svg")),
  BookAlt: lazy(async () => import("./assets/book-alt.svg")),
  BookAltSolid: lazy(async () => import("./assets/book-alt-solid.svg")),
  Bookmark: lazy(async () => import("./assets/bookmark.svg")),
  BookmarkSolid: lazy(async () => import("./assets/bookmark-solid.svg")),
  BookSolid: lazy(async () => import("./assets/book-solid.svg")),
  Bowling: lazy(async () => import("./assets/bowling.svg")),
  BowlingSolid: lazy(async () => import("./assets/bowling-solid.svg")),
  Box: lazy(async () => import("./assets/box.svg")),
  BoxAlt: lazy(async () => import("./assets/box-alt.svg")),
  BoxAltSolid: lazy(async () => import("./assets/box-alt-solid.svg")),
  BoxSolid: lazy(async () => import("./assets/box-solid.svg")),
  BreadSlice: lazy(async () => import("./assets/bread-slice.svg")),
  BreadSliceSolid: lazy(async () => import("./assets/bread-slice-solid.svg")),
  Briefcase: lazy(async () => import("./assets/briefcase.svg")),
  BriefcaseSolid: lazy(async () => import("./assets/briefcase-solid.svg")),
  Broom: lazy(async () => import("./assets/broom.svg")),
  BroomSolid: lazy(async () => import("./assets/broom-solid.svg")),
  Browser: lazy(async () => import("./assets/browser.svg")),
  BrowserSolid: lazy(async () => import("./assets/browser-solid.svg")),
  Brush: lazy(async () => import("./assets/brush.svg")),
  BrushSolid: lazy(async () => import("./assets/brush-solid.svg")),
  Bug: lazy(async () => import("./assets/bug.svg")),
  BugSolid: lazy(async () => import("./assets/bug-solid.svg")),
  Building: lazy(async () => import("./assets/building.svg")),
  BuildingSolid: lazy(async () => import("./assets/building-solid.svg")),
  Bulb: lazy(async () => import("./assets/bulb.svg")),
  BulbSolid: lazy(async () => import("./assets/bulb-solid.svg")),
  Butterfly: lazy(async () => import("./assets/butterfly.svg")),
  ButterflySolid: lazy(async () => import("./assets/butterfly-solid.svg")),
  Calculator: lazy(async () => import("./assets/calculator.svg")),
  CalculatorSolid: lazy(async () => import("./assets/calculator-solid.svg")),
  Calendar: lazy(async () => import("./assets/calendar.svg")),
  CalendarSolid: lazy(async () => import("./assets/calendar-solid.svg")),
  CallIncoming: lazy(async () => import("./assets/call-incoming.svg")),
  CallIncomingSolid: lazy(
    async () => import("./assets/call-incoming-solid.svg")
  ),
  Camera: lazy(async () => import("./assets/camera.svg")),
  CameraSolid: lazy(async () => import("./assets/camera-solid.svg")),
  Camping: lazy(async () => import("./assets/camping.svg")),
  CampingSolid: lazy(async () => import("./assets/camping-solid.svg")),
  Car: lazy(async () => import("./assets/car.svg")),
  CaretDown: lazy(async () => import("./assets/caret-down.svg")),
  Carrot: lazy(async () => import("./assets/carrot.svg")),
  CarrotSolid: lazy(async () => import("./assets/carrot-solid.svg")),
  CarSolid: lazy(async () => import("./assets/car-solid.svg")),
  ChartArrowDown: lazy(async () => import("./assets/chart-arrow-down.svg")),
  ChartArrowGrow: lazy(async () => import("./assets/chart-arrow-grow.svg")),
  ChartConnected: lazy(async () => import("./assets/chart-connected.svg")),
  ChartConnectedSolid: lazy(
    async () => import("./assets/chart-connected-solid.svg")
  ),
  ChartHistogram: lazy(async () => import("./assets/chart-histogram.svg")),
  ChartNetwork: lazy(async () => import("./assets/chart-network.svg")),
  ChartNetworkSolid: lazy(
    async () => import("./assets/chart-network-solid.svg")
  ),
  ChartPie: lazy(async () => import("./assets/chart-pie.svg")),
  ChartPieAlt: lazy(async () => import("./assets/chart-pie-alt.svg")),
  ChartPieAltSolid: lazy(
    async () => import("./assets/chart-pie-alt-solid.svg")
  ),
  ChartPieSolid: lazy(async () => import("./assets/chart-pie-solid.svg")),
  ChartPyramid: lazy(async () => import("./assets/chart-pyramid.svg")),
  ChartPyramidSolid: lazy(
    async () => import("./assets/chart-pyramid-solid.svg")
  ),
  ChartSetTheory: lazy(async () => import("./assets/chart-set-theory.svg")),
  ChartSetTheorySolid: lazy(
    async () => import("./assets/chart-set-theory-solid.svg")
  ),
  ChartTree: lazy(async () => import("./assets/chart-tree.svg")),
  ChartTreeSolid: lazy(async () => import("./assets/chart-tree-solid.svg")),
  Check: lazy(async () => import("./assets/check.svg")),
  Checkbox: lazy(async () => import("./assets/checkbox.svg")),
  CheckboxSolid: lazy(async () => import("./assets/checkbox-solid.svg")),
  ChessPiece: lazy(async () => import("./assets/chess-piece.svg")),
  ChessPieceSolid: lazy(async () => import("./assets/chess-piece-solid.svg")),
  ChildHead: lazy(async () => import("./assets/child-head.svg")),
  ChildHeadSolid: lazy(async () => import("./assets/child-head-solid.svg")),
  Circle: lazy(async () => import("./assets/circle.svg")),
  Clip: lazy(async () => import("./assets/clip.svg")),
  ClipSolid: lazy(async () => import("./assets/clip-solid.svg")),
  Clock: lazy(async () => import("./assets/clock.svg")),
  ClockSolid: lazy(async () => import("./assets/clock-solid.svg")),
  Cloud: lazy(async () => import("./assets/cloud.svg")),
  CloudCheck: lazy(async () => import("./assets/cloud-check.svg")),
  CloudCheckSolid: lazy(async () => import("./assets/cloud-check-solid.svg")),
  CloudDisabled: lazy(async () => import("./assets/cloud-disabled.svg")),
  CloudDisabledSolid: lazy(
    async () => import("./assets/cloud-disabled-solid.svg")
  ),
  CloudDownload: lazy(async () => import("./assets/cloud-download.svg")),
  CloudDownloadSolid: lazy(
    async () => import("./assets/cloud-download-solid.svg")
  ),
  Clouds: lazy(async () => import("./assets/clouds.svg")),
  CloudShare: lazy(async () => import("./assets/cloud-share.svg")),
  CloudShareSolid: lazy(async () => import("./assets/cloud-share-solid.svg")),
  CloudSolid: lazy(async () => import("./assets/cloud-solid.svg")),
  CloudsSolid: lazy(async () => import("./assets/clouds-solid.svg")),
  CloudUpload: lazy(async () => import("./assets/cloud-upload.svg")),
  CloudUploadSolid: lazy(async () => import("./assets/cloud-upload-solid.svg")),
  Cocktail: lazy(async () => import("./assets/cocktail.svg")),
  CocktailSolid: lazy(async () => import("./assets/cocktail-solid.svg")),
  Coffee: lazy(async () => import("./assets/coffee.svg")),
  CoffeeSolid: lazy(async () => import("./assets/coffee-solid.svg")),
  Comment: lazy(async () => import("./assets/comment.svg")),
  CommentAlt: lazy(async () => import("./assets/comment-alt.svg")),
  CommentAltSolid: lazy(async () => import("./assets/comment-alt-solid.svg")),
  CommentCheck: lazy(async () => import("./assets/comment-check.svg")),
  CommentCheckSolid: lazy(
    async () => import("./assets/comment-check-solid.svg")
  ),
  CommentHeart: lazy(async () => import("./assets/comment-heart.svg")),
  CommentHeartSolid: lazy(
    async () => import("./assets/comment-heart-solid.svg")
  ),
  CommentInfo: lazy(async () => import("./assets/comment-info.svg")),
  CommentInfoSolid: lazy(async () => import("./assets/comment-info-solid.svg")),
  Comments: lazy(async () => import("./assets/comments.svg")),
  CommentSolid: lazy(async () => import("./assets/comment-solid.svg")),
  CommentsSolid: lazy(async () => import("./assets/comments-solid.svg")),
  CommentUser: lazy(async () => import("./assets/comment-user.svg")),
  CommentUserSolid: lazy(async () => import("./assets/comment-user-solid.svg")),
  Compress: lazy(async () => import("./assets/compress.svg")),
  CompressAlt: lazy(async () => import("./assets/compress-alt.svg")),
  Computer: lazy(async () => import("./assets/computer.svg")),
  ComputerSolid: lazy(async () => import("./assets/computer-solid.svg")),
  Confetti: lazy(async () => import("./assets/confetti.svg")),
  Cookie: lazy(async () => import("./assets/cookie.svg")),
  CookieSolid: lazy(async () => import("./assets/cookie-solid.svg")),
  Copy: lazy(async () => import("./assets/copy.svg")),
  CopyAlt: lazy(async () => import("./assets/copy-alt.svg")),
  CopyAltSolid: lazy(async () => import("./assets/copy-alt-solid.svg")),
  Copyright: lazy(async () => import("./assets/copyright.svg")),
  CopyrightSolid: lazy(async () => import("./assets/copyright-solid.svg")),
  CopySolid: lazy(async () => import("./assets/copy-solid.svg")),
  Cow: lazy(async () => import("./assets/cow.svg")),
  CowSolid: lazy(async () => import("./assets/cow-solid.svg")),
  Cream: lazy(async () => import("./assets/cream.svg")),
  CreamSolid: lazy(async () => import("./assets/cream-solid.svg")),
  CreditCard: lazy(async () => import("./assets/credit-card.svg")),
  CreditCardSolid: lazy(async () => import("./assets/credit-card-solid.svg")),
  Croissant: lazy(async () => import("./assets/croissant.svg")),
  CroissantSolid: lazy(async () => import("./assets/croissant-solid.svg")),
  Cross: lazy(async () => import("./assets/cross.svg")),
  CrossCircle: lazy(async () => import("./assets/cross-circle.svg")),
  CrossCircleSolid: lazy(async () => import("./assets/cross-circle-solid.svg")),
  CrossSmall: lazy(async () => import("./assets/cross-small.svg")),
  Crown: lazy(async () => import("./assets/crown.svg")),
  CrownSolid: lazy(async () => import("./assets/crown-solid.svg")),
  Cube: lazy(async () => import("./assets/cube.svg")),
  CubeSolid: lazy(async () => import("./assets/cube-solid.svg")),
  Cupcake: lazy(async () => import("./assets/cupcake.svg")),
  CupcakeSolid: lazy(async () => import("./assets/cupcake-solid.svg")),
  Cursor: lazy(async () => import("./assets/cursor.svg")),
  CursorFinger: lazy(async () => import("./assets/cursor-finger.svg")),
  CursorFingerSolid: lazy(
    async () => import("./assets/cursor-finger-solid.svg")
  ),
  CursorPlus: lazy(async () => import("./assets/cursor-plus.svg")),
  CursorPlusSolid: lazy(async () => import("./assets/cursor-plus-solid.svg")),
  CursorSolid: lazy(async () => import("./assets/cursor-solid.svg")),
  CursorText: lazy(async () => import("./assets/cursor-text.svg")),
  CursorTextAlt: lazy(async () => import("./assets/cursor-text-alt.svg")),
  CursorTextAltSolid: lazy(
    async () => import("./assets/cursor-text-alt-solid.svg")
  ),
  Dart: lazy(async () => import("./assets/dart.svg")),
  DartSolid: lazy(async () => import("./assets/dart-solid.svg")),
  Dashboard: lazy(async () => import("./assets/dashboard.svg")),
  DashboardSolid: lazy(async () => import("./assets/dashboard-solid.svg")),
  Database: lazy(async () => import("./assets/database.svg")),
  DatabaseSolid: lazy(async () => import("./assets/database-solid.svg")),
  DataTransfer: lazy(async () => import("./assets/data-transfer.svg")),
  DataTransferSolid: lazy(
    async () => import("./assets/data-transfer-solid.svg")
  ),
  Delete: lazy(async () => import("./assets/delete.svg")),
  DeleteSolid: lazy(async () => import("./assets/delete-solid.svg")),
  Diamond: lazy(async () => import("./assets/diamond.svg")),
  DiamondSolid: lazy(async () => import("./assets/diamond-solid.svg")),
  Dice: lazy(async () => import("./assets/dice.svg")),
  DiceSolid: lazy(async () => import("./assets/dice-solid.svg")),
  Diploma: lazy(async () => import("./assets/diploma.svg")),
  DiplomaSolid: lazy(async () => import("./assets/diploma-solid.svg")),
  DiscoBall: lazy(async () => import("./assets/disco-ball.svg")),
  DiscoBallSolid: lazy(async () => import("./assets/disco-ball-solid.svg")),
  Disk: lazy(async () => import("./assets/disk.svg")),
  DiskSolid: lazy(async () => import("./assets/disk-solid.svg")),
  Doctor: lazy(async () => import("./assets/doctor.svg")),
  DoctorSolid: lazy(async () => import("./assets/doctor-solid.svg")),
  DocumentSigned: lazy(async () => import("./assets/document-signed.svg")),
  DocumentSignedSolid: lazy(
    async () => import("./assets/document-signed-solid.svg")
  ),
  Dollar: lazy(async () => import("./assets/dollar.svg")),
  Download: lazy(async () => import("./assets/download.svg")),
  DrinkAlt: lazy(async () => import("./assets/drink-alt.svg")),
  DrinkAltSolid: lazy(async () => import("./assets/drink-alt-solid.svg")),
  Drumstick: lazy(async () => import("./assets/drumstick.svg")),
  DrumstickSolid: lazy(async () => import("./assets/drumstick-solid.svg")),
  Duplicate: lazy(async () => import("./assets/duplicate.svg")),
  DuplicateSolid: lazy(async () => import("./assets/duplicate-solid.svg")),
  Earnings: lazy(async () => import("./assets/earnings.svg")),
  Edit: lazy(async () => import("./assets/edit.svg")),
  EditAlt: lazy(async () => import("./assets/edit-alt.svg")),
  EditAltSolid: lazy(async () => import("./assets/edit-alt-solid.svg")),
  EditSolid: lazy(async () => import("./assets/edit-solid.svg")),
  ELearning: lazy(async () => import("./assets/e-learning.svg")),
  ELearningSolid: lazy(async () => import("./assets/e-learning-solid.svg")),
  Envelope: lazy(async () => import("./assets/envelope.svg")),
  EnvelopeBan: lazy(async () => import("./assets/envelope-ban.svg")),
  EnvelopeBanSolid: lazy(async () => import("./assets/envelope-ban-solid.svg")),
  EnvelopeDownload: lazy(async () => import("./assets/envelope-download.svg")),
  EnvelopeDownloadSolid: lazy(
    async () => import("./assets/envelope-download-solid.svg")
  ),
  EnvelopeMarker: lazy(async () => import("./assets/envelope-marker.svg")),
  EnvelopeMarkerSolid: lazy(
    async () => import("./assets/envelope-marker-solid.svg")
  ),
  EnvelopeOpen: lazy(async () => import("./assets/envelope-open.svg")),
  EnvelopeOpenSolid: lazy(
    async () => import("./assets/envelope-open-solid.svg")
  ),
  EnvelopePlus: lazy(async () => import("./assets/envelope-plus.svg")),
  EnvelopePlusSolid: lazy(
    async () => import("./assets/envelope-plus-solid.svg")
  ),
  EnvelopeSolid: lazy(async () => import("./assets/envelope-solid.svg")),
  Euro: lazy(async () => import("./assets/euro.svg")),
  Exclamation: lazy(async () => import("./assets/exclamation.svg")),
  ExclamationSolid: lazy(async () => import("./assets/exclamation-solid.svg")),
  Expand: lazy(async () => import("./assets/expand.svg")),
  Eye: lazy(async () => import("./assets/eye.svg")),
  EyeCrossed: lazy(async () => import("./assets/eye-crossed.svg")),
  EyeCrossedSolid: lazy(async () => import("./assets/eye-crossed-solid.svg")),
  EyeDropper: lazy(async () => import("./assets/eye-dropper.svg")),
  EyeDropperSolid: lazy(async () => import("./assets/eye-dropper-solid.svg")),
  EyeSolid: lazy(async () => import("./assets/eye-solid.svg")),
  Feather: lazy(async () => import("./assets/feather.svg")),
  FeatherSolid: lazy(async () => import("./assets/feather-solid.svg")),
  FerrisWheel: lazy(async () => import("./assets/ferris-wheel.svg")),
  FerrisWheelSolid: lazy(async () => import("./assets/ferris-wheel-solid.svg")),
  File: lazy(async () => import("./assets/file.svg")),
  FileAdd: lazy(async () => import("./assets/file-add.svg")),
  FileAddSolid: lazy(async () => import("./assets/file-add-solid.svg")),
  FileAi: lazy(async () => import("./assets/file-ai.svg")),
  FileAiSolid: lazy(async () => import("./assets/file-ai-solid.svg")),
  FileCheck: lazy(async () => import("./assets/file-check.svg")),
  FileCheckSolid: lazy(async () => import("./assets/file-check-solid.svg")),
  FileDelete: lazy(async () => import("./assets/file-delete.svg")),
  FileDeleteSolid: lazy(async () => import("./assets/file-delete-solid.svg")),
  FileEps: lazy(async () => import("./assets/file-eps.svg")),
  FileEpsSolid: lazy(async () => import("./assets/file-eps-solid.svg")),
  FileGif: lazy(async () => import("./assets/file-gif.svg")),
  FileGifSolid: lazy(async () => import("./assets/file-gif-solid.svg")),
  FileJpg: lazy(async () => import("./assets/file-jpg.svg")),
  FileJpgSolid: lazy(async () => import("./assets/file-jpg-solid.svg")),
  FileMusic: lazy(async () => import("./assets/file-music.svg")),
  FileMusicSolid: lazy(async () => import("./assets/file-music-solid.svg")),
  FilePsd: lazy(async () => import("./assets/file-psd.svg")),
  FilePsdSolid: lazy(async () => import("./assets/file-psd-solid.svg")),
  FileSolid: lazy(async () => import("./assets/file-solid.svg")),
  Fill: lazy(async () => import("./assets/fill.svg")),
  FillSolid: lazy(async () => import("./assets/fill-solid.svg")),
  Film: lazy(async () => import("./assets/film.svg")),
  FilmSolid: lazy(async () => import("./assets/film-solid.svg")),
  Filter: lazy(async () => import("./assets/filter.svg")),
  FilterSolid: lazy(async () => import("./assets/filter-solid.svg")),
  Fingerprint: lazy(async () => import("./assets/fingerprint.svg")),
  Fish: lazy(async () => import("./assets/fish.svg")),
  FishSolid: lazy(async () => import("./assets/fish-solid.svg")),
  Flag: lazy(async () => import("./assets/flag.svg")),
  FlagSolid: lazy(async () => import("./assets/flag-solid.svg")),
  Flame: lazy(async () => import("./assets/flame.svg")),
  FlameSolid: lazy(async () => import("./assets/flame-solid.svg")),
  FlipHorizontal: lazy(async () => import("./assets/flip-horizontal.svg")),
  Flower: lazy(async () => import("./assets/flower.svg")),
  FlowerBouquet: lazy(async () => import("./assets/flower-bouquet.svg")),
  FlowerBouquetSolid: lazy(
    async () => import("./assets/flower-bouquet-solid.svg")
  ),
  FlowerSolid: lazy(async () => import("./assets/flower-solid.svg")),
  FlowerTulip: lazy(async () => import("./assets/flower-tulip.svg")),
  FlowerTulipSolid: lazy(async () => import("./assets/flower-tulip-solid.svg")),
  Folder: lazy(async () => import("./assets/folder.svg")),
  FolderAdd: lazy(async () => import("./assets/folder-add.svg")),
  FolderAddSolid: lazy(async () => import("./assets/folder-add-solid.svg")),
  FolderSolid: lazy(async () => import("./assets/folder-solid.svg")),
  Following: lazy(async () => import("./assets/following.svg")),
  FollowingSolid: lazy(async () => import("./assets/following-solid.svg")),
  Football: lazy(async () => import("./assets/football.svg")),
  FootballSolid: lazy(async () => import("./assets/football-solid.svg")),
  Form: lazy(async () => import("./assets/form.svg")),
  FormSolid: lazy(async () => import("./assets/form-solid.svg")),
  Forward: lazy(async () => import("./assets/forward.svg")),
  ForwardSolid: lazy(async () => import("./assets/forward-solid.svg")),
  Fox: lazy(async () => import("./assets/fox.svg")),
  FoxSolid: lazy(async () => import("./assets/fox-solid.svg")),
  Frown: lazy(async () => import("./assets/frown.svg")),
  FrownSolid: lazy(async () => import("./assets/frown-solid.svg")),
  Ftp: lazy(async () => import("./assets/ftp.svg")),
  FtpSolid: lazy(async () => import("./assets/ftp-solid.svg")),
  Gallery: lazy(async () => import("./assets/gallery.svg")),
  GallerySolid: lazy(async () => import("./assets/gallery-solid.svg")),
  Gamepad: lazy(async () => import("./assets/gamepad.svg")),
  GamepadSolid: lazy(async () => import("./assets/gamepad-solid.svg")),
  GasPump: lazy(async () => import("./assets/gas-pump.svg")),
  GasPumpSolid: lazy(async () => import("./assets/gas-pump-solid.svg")),
  Gem: lazy(async () => import("./assets/gem.svg")),
  GemSolid: lazy(async () => import("./assets/gem-solid.svg")),
  Gift: lazy(async () => import("./assets/gift.svg")),
  GiftSolid: lazy(async () => import("./assets/gift-solid.svg")),
  GlassCheers: lazy(async () => import("./assets/glass-cheers.svg")),
  GlassCheersSolid: lazy(async () => import("./assets/glass-cheers-solid.svg")),
  Glasses: lazy(async () => import("./assets/glasses.svg")),
  GlassesSolid: lazy(async () => import("./assets/glasses-solid.svg")),
  Globe: lazy(async () => import("./assets/globe.svg")),
  GlobeAlt: lazy(async () => import("./assets/globe-alt.svg")),
  GlobeAltSolid: lazy(async () => import("./assets/globe-alt-solid.svg")),
  GlobeSolid: lazy(async () => import("./assets/globe-solid.svg")),
  GraduationCap: lazy(async () => import("./assets/graduation-cap.svg")),
  GraduationCapSolid: lazy(
    async () => import("./assets/graduation-cap-solid.svg")
  ),
  GraphicTablet: lazy(async () => import("./assets/graphic-tablet.svg")),
  GraphicTabletSolid: lazy(
    async () => import("./assets/graphic-tablet-solid.svg")
  ),
  Grid: lazy(async () => import("./assets/grid.svg")),
  GridAlt: lazy(async () => import("./assets/grid-alt.svg")),
  GridAltSolid: lazy(async () => import("./assets/grid-alt-solid.svg")),
  GridSolid: lazy(async () => import("./assets/grid-solid.svg")),
  Guitar: lazy(async () => import("./assets/guitar.svg")),
  GuitarSolid: lazy(async () => import("./assets/guitar-solid.svg")),
  Gym: lazy(async () => import("./assets/gym.svg")),
  GymSolid: lazy(async () => import("./assets/gym-solid.svg")),
  Hamburger: lazy(async () => import("./assets/hamburger.svg")),
  HamburgerSolid: lazy(async () => import("./assets/hamburger-solid.svg")),
  HandHoldingHeart: lazy(async () => import("./assets/hand-holding-heart.svg")),
  HandHoldingHeartSolid: lazy(
    async () => import("./assets/hand-holding-heart-solid.svg")
  ),
  Hashtag: lazy(async () => import("./assets/hashtag.svg")),
  HatBirthday: lazy(async () => import("./assets/hat-birthday.svg")),
  HatBirthdaySolid: lazy(async () => import("./assets/hat-birthday-solid.svg")),
  Headphones: lazy(async () => import("./assets/headphones.svg")),
  HeadphonesSolid: lazy(async () => import("./assets/headphones-solid.svg")),
  Headset: lazy(async () => import("./assets/headset.svg")),
  HeadsetSolid: lazy(async () => import("./assets/headset-solid.svg")),
  HeadSideThinking: lazy(async () => import("./assets/head-side-thinking.svg")),
  HeadSideThinkingSolid: lazy(
    async () => import("./assets/head-side-thinking-solid.svg")
  ),
  Heart: lazy(async () => import("./assets/heart.svg")),
  HeartArrow: lazy(async () => import("./assets/heart-arrow.svg")),
  HeartArrowSolid: lazy(async () => import("./assets/heart-arrow-solid.svg")),
  HeartSolid: lazy(async () => import("./assets/heart-solid.svg")),
  Home: lazy(async () => import("./assets/home.svg")),
  HomeLocation: lazy(async () => import("./assets/home-location.svg")),
  HomeLocationAlt: lazy(async () => import("./assets/home-location-alt.svg")),
  HomeLocationAltSolid: lazy(
    async () => import("./assets/home-location-alt-solid.svg")
  ),
  HomeLocationSolid: lazy(
    async () => import("./assets/home-location-solid.svg")
  ),
  HomeSolid: lazy(async () => import("./assets/home-solid.svg")),
  Hourglass: lazy(async () => import("./assets/hourglass.svg")),
  HourglassEnd: lazy(async () => import("./assets/hourglass-end.svg")),
  HourglassEndSolid: lazy(
    async () => import("./assets/hourglass-end-solid.svg")
  ),
  HourglassSolid: lazy(async () => import("./assets/hourglass-solid.svg")),
  IceCream: lazy(async () => import("./assets/ice-cream.svg")),
  IceCreamSolid: lazy(async () => import("./assets/ice-cream-solid.svg")),
  IceSkate: lazy(async () => import("./assets/ice-skate.svg")),
  IceSkateSolid: lazy(async () => import("./assets/ice-skate-solid.svg")),
  IdBadge: lazy(async () => import("./assets/id-badge.svg")),
  IdBadgeSolid: lazy(async () => import("./assets/id-badge-solid.svg")),
  Inbox: lazy(async () => import("./assets/inbox.svg")),
  InboxSolid: lazy(async () => import("./assets/inbox-solid.svg")),
  Incognito: lazy(async () => import("./assets/incognito.svg")),
  IncognitoSolid: lazy(async () => import("./assets/incognito-solid.svg")),
  Indent: lazy(async () => import("./assets/indent.svg")),
  Infinity: lazy(async () => import("./assets/infinity.svg")),
  Info: lazy(async () => import("./assets/info.svg")),
  InfoSolid: lazy(async () => import("./assets/info-solid.svg")),
  Interactive: lazy(async () => import("./assets/interactive.svg")),
  InteractiveSolid: lazy(async () => import("./assets/interactive-solid.svg")),
  Interlining: lazy(async () => import("./assets/interlining.svg")),
  Interrogation: lazy(async () => import("./assets/interrogation.svg")),
  InterrogationSolid: lazy(
    async () => import("./assets/interrogation-solid.svg")
  ),
  Italic: lazy(async () => import("./assets/italic.svg")),
  Key: lazy(async () => import("./assets/key.svg")),
  Keyboard: lazy(async () => import("./assets/keyboard.svg")),
  KeyboardSolid: lazy(async () => import("./assets/keyboard-solid.svg")),
  KeySolid: lazy(async () => import("./assets/key-solid.svg")),
  Kite: lazy(async () => import("./assets/kite.svg")),
  KiteSolid: lazy(async () => import("./assets/kite-solid.svg")),
  Label: lazy(async () => import("./assets/label.svg")),
  LabelSolid: lazy(async () => import("./assets/label-solid.svg")),
  Laptop: lazy(async () => import("./assets/laptop.svg")),
  LaptopSolid: lazy(async () => import("./assets/laptop-solid.svg")),
  Lasso: lazy(async () => import("./assets/lasso.svg")),
  Laugh: lazy(async () => import("./assets/laugh.svg")),
  LaughSolid: lazy(async () => import("./assets/laugh-solid.svg")),
  Layers: lazy(async () => import("./assets/layers.svg")),
  LayersSolid: lazy(async () => import("./assets/layers-solid.svg")),
  LayoutFluid: lazy(async () => import("./assets/layout-fluid.svg")),
  LayoutFluidSolid: lazy(async () => import("./assets/layout-fluid-solid.svg")),
  Leaf: lazy(async () => import("./assets/leaf.svg")),
  LeafSolid: lazy(async () => import("./assets/leaf-solid.svg")),
  LetterCase: lazy(async () => import("./assets/letter-case.svg")),
  LifeRing: lazy(async () => import("./assets/life-ring.svg")),
  LifeRingSolid: lazy(async () => import("./assets/life-ring-solid.svg")),
  LineWidth: lazy(async () => import("./assets/line-width.svg")),
  Link: lazy(async () => import("./assets/link.svg")),
  Lipstick: lazy(async () => import("./assets/lipstick.svg")),
  LipstickSolid: lazy(async () => import("./assets/lipstick-solid.svg")),
  List: lazy(async () => import("./assets/list.svg")),
  ListCheck: lazy(async () => import("./assets/list-check.svg")),
  LocationAlt: lazy(async () => import("./assets/location-alt.svg")),
  LocationAltSolid: lazy(async () => import("./assets/location-alt-solid.svg")),
  Lock: lazy(async () => import("./assets/lock.svg")),
  LockAlt: lazy(async () => import("./assets/lock-alt.svg")),
  LockAltSolid: lazy(async () => import("./assets/lock-alt-solid.svg")),
  LockSolid: lazy(async () => import("./assets/lock-solid.svg")),
  LuggageRolling: lazy(async () => import("./assets/luggage-rolling.svg")),
  LuggageRollingSolid: lazy(
    async () => import("./assets/luggage-rolling-solid.svg")
  ),
  MagicWand: lazy(async () => import("./assets/magic-wand.svg")),
  MagicWandSolid: lazy(async () => import("./assets/magic-wand-solid.svg")),
  MakeupBrush: lazy(async () => import("./assets/makeup-brush.svg")),
  MakeupBrushSolid: lazy(async () => import("./assets/makeup-brush-solid.svg")),
  ManHead: lazy(async () => import("./assets/man-head.svg")),
  ManHeadSolid: lazy(async () => import("./assets/man-head-solid.svg")),
  Map: lazy(async () => import("./assets/map.svg")),
  MapMarker: lazy(async () => import("./assets/map-marker.svg")),
  MapMarkerCross: lazy(async () => import("./assets/map-marker-cross.svg")),
  MapMarkerCrossSolid: lazy(
    async () => import("./assets/map-marker-cross-solid.svg")
  ),
  MapMarkerHome: lazy(async () => import("./assets/map-marker-home.svg")),
  MapMarkerHomeSolid: lazy(
    async () => import("./assets/map-marker-home-solid.svg")
  ),
  MapMarkerMinus: lazy(async () => import("./assets/map-marker-minus.svg")),
  MapMarkerMinusSolid: lazy(
    async () => import("./assets/map-marker-minus-solid.svg")
  ),
  MapMarkerPlus: lazy(async () => import("./assets/map-marker-plus.svg")),
  MapMarkerPlusSolid: lazy(
    async () => import("./assets/map-marker-plus-solid.svg")
  ),
  MapMarkerSolid: lazy(async () => import("./assets/map-marker-solid.svg")),
  MapSolid: lazy(async () => import("./assets/map-solid.svg")),
  Marker: lazy(async () => import("./assets/marker.svg")),
  MarkerSolid: lazy(async () => import("./assets/marker-solid.svg")),
  MarkerTime: lazy(async () => import("./assets/marker-time.svg")),
  MarkerTimeSolid: lazy(async () => import("./assets/marker-time-solid.svg")),
  Mars: lazy(async () => import("./assets/mars.svg")),
  MarsDouble: lazy(async () => import("./assets/mars-double.svg")),
  MarsDoubleSolid: lazy(async () => import("./assets/mars-double-solid.svg")),
  MarsSolid: lazy(async () => import("./assets/mars-solid.svg")),
  Medicine: lazy(async () => import("./assets/medicine.svg")),
  MedicineSolid: lazy(async () => import("./assets/medicine-solid.svg")),
  Megaphone: lazy(async () => import("./assets/megaphone.svg")),
  MegaphoneSolid: lazy(async () => import("./assets/megaphone-solid.svg")),
  Meh: lazy(async () => import("./assets/meh.svg")),
  MehSolid: lazy(async () => import("./assets/meh-solid.svg")),
  MenuBurger: lazy(async () => import("./assets/menu-burger.svg")),
  MenuDots: lazy(async () => import("./assets/menu-dots.svg")),
  Microphone: lazy(async () => import("./assets/microphone.svg")),
  MicrophoneAlt: lazy(async () => import("./assets/microphone-alt.svg")),
  MicrophoneAltSolid: lazy(
    async () => import("./assets/microphone-alt-solid.svg")
  ),
  MicrophoneSolid: lazy(async () => import("./assets/microphone-solid.svg")),
  Minus: lazy(async () => import("./assets/minus.svg")),
  MinusSmall: lazy(async () => import("./assets/minus-small.svg")),
  Mobile: lazy(async () => import("./assets/mobile.svg")),
  MobileSolid: lazy(async () => import("./assets/mobile-solid.svg")),
  ModeLandscape: lazy(async () => import("./assets/mode-landscape.svg")),
  ModeLandscapeSolid: lazy(
    async () => import("./assets/mode-landscape-solid.svg")
  ),
  ModePortrait: lazy(async () => import("./assets/mode-portrait.svg")),
  ModePortraitSolid: lazy(
    async () => import("./assets/mode-portrait-solid.svg")
  ),
  Money: lazy(async () => import("./assets/money.svg")),
  MoneySolid: lazy(async () => import("./assets/money-solid.svg")),
  Moon: lazy(async () => import("./assets/moon.svg")),
  MoonSolid: lazy(async () => import("./assets/moon-solid.svg")),
  Mountains: lazy(async () => import("./assets/mountains.svg")),
  MountainsSolid: lazy(async () => import("./assets/mountains-solid.svg")),
  Mouse: lazy(async () => import("./assets/mouse.svg")),
  MouseSolid: lazy(async () => import("./assets/mouse-solid.svg")),
  MugAlt: lazy(async () => import("./assets/mug-alt.svg")),
  MugAltSolid: lazy(async () => import("./assets/mug-alt-solid.svg")),
  Music: lazy(async () => import("./assets/music.svg")),
  MusicAlt: lazy(async () => import("./assets/music-alt.svg")),
  MusicAltSolid: lazy(async () => import("./assets/music-alt-solid.svg")),
  MusicSolid: lazy(async () => import("./assets/music-solid.svg")),
  Navigation: lazy(async () => import("./assets/navigation.svg")),
  NavigationSolid: lazy(async () => import("./assets/navigation-solid.svg")),
  Network: lazy(async () => import("./assets/network.svg")),
  NetworkCloud: lazy(async () => import("./assets/network-cloud.svg")),
  NetworkCloudSolid: lazy(
    async () => import("./assets/network-cloud-solid.svg")
  ),
  NetworkSolid: lazy(async () => import("./assets/network-solid.svg")),
  Notebook: lazy(async () => import("./assets/notebook.svg")),
  NotebookSolid: lazy(async () => import("./assets/notebook-solid.svg")),
  Opacity: lazy(async () => import("./assets/opacity.svg")),
  Package: lazy(async () => import("./assets/package.svg")),
  PackageSolid: lazy(async () => import("./assets/package-solid.svg")),
  PaintBrush: lazy(async () => import("./assets/paint-brush.svg")),
  PaintBrushSolid: lazy(async () => import("./assets/paint-brush-solid.svg")),
  Palette: lazy(async () => import("./assets/palette.svg")),
  PaletteSolid: lazy(async () => import("./assets/palette-solid.svg")),
  PaperPlane: lazy(async () => import("./assets/paper-plane.svg")),
  PaperPlaneSolid: lazy(async () => import("./assets/paper-plane-solid.svg")),
  Password: lazy(async () => import("./assets/password.svg")),
  Pause: lazy(async () => import("./assets/pause.svg")),
  PauseSolid: lazy(async () => import("./assets/pause-solid.svg")),
  Paw: lazy(async () => import("./assets/paw.svg")),
  PawSolid: lazy(async () => import("./assets/paw-solid.svg")),
  Pencil: lazy(async () => import("./assets/pencil.svg")),
  PencilSolid: lazy(async () => import("./assets/pencil-solid.svg")),
  Pharmacy: lazy(async () => import("./assets/pharmacy.svg")),
  PharmacySolid: lazy(async () => import("./assets/pharmacy-solid.svg")),
  PhoneCall: lazy(async () => import("./assets/phone-call.svg")),
  PhoneCallSolid: lazy(async () => import("./assets/phone-call-solid.svg")),
  PhoneCross: lazy(async () => import("./assets/phone-cross.svg")),
  PhoneCrossSolid: lazy(async () => import("./assets/phone-cross-solid.svg")),
  PhonePause: lazy(async () => import("./assets/phone-pause.svg")),
  PhonePauseSolid: lazy(async () => import("./assets/phone-pause-solid.svg")),
  PhoneSlash: lazy(async () => import("./assets/phone-slash.svg")),
  PhoneSlashSolid: lazy(async () => import("./assets/phone-slash-solid.svg")),
  Physics: lazy(async () => import("./assets/physics.svg")),
  Picture: lazy(async () => import("./assets/picture.svg")),
  PictureSolid: lazy(async () => import("./assets/picture-solid.svg")),
  PingPong: lazy(async () => import("./assets/ping-pong.svg")),
  PingPongSolid: lazy(async () => import("./assets/ping-pong-solid.svg")),
  PizzaSlice: lazy(async () => import("./assets/pizza-slice.svg")),
  PizzaSliceSolid: lazy(async () => import("./assets/pizza-slice-solid.svg")),
  Plane: lazy(async () => import("./assets/plane.svg")),
  PlaneSolid: lazy(async () => import("./assets/plane-solid.svg")),
  Play: lazy(async () => import("./assets/play.svg")),
  PlayAlt: lazy(async () => import("./assets/play-alt.svg")),
  PlayAltSolid: lazy(async () => import("./assets/play-alt-solid.svg")),
  PlayingCards: lazy(async () => import("./assets/playing-cards.svg")),
  PlayingCardsSolid: lazy(
    async () => import("./assets/playing-cards-solid.svg")
  ),
  PlaySolid: lazy(async () => import("./assets/play-solid.svg")),
  Plus: lazy(async () => import("./assets/plus.svg")),
  PlusSmall: lazy(async () => import("./assets/plus-small.svg")),
  PokerChip: lazy(async () => import("./assets/poker-chip.svg")),
  PokerChipSolid: lazy(async () => import("./assets/poker-chip-solid.svg")),
  Portrait: lazy(async () => import("./assets/portrait.svg")),
  PortraitSolid: lazy(async () => import("./assets/portrait-solid.svg")),
  Pound: lazy(async () => import("./assets/pound.svg")),
  PoundSolid: lazy(async () => import("./assets/pound-solid.svg")),
  Power: lazy(async () => import("./assets/power.svg")),
  Presentation: lazy(async () => import("./assets/presentation.svg")),
  PresentationSolid: lazy(
    async () => import("./assets/presentation-solid.svg")
  ),
  Print: lazy(async () => import("./assets/print.svg")),
  PrintSolid: lazy(async () => import("./assets/print-solid.svg")),
  Protractor: lazy(async () => import("./assets/protractor.svg")),
  ProtractorSolid: lazy(async () => import("./assets/protractor-solid.svg")),
  Pulse: lazy(async () => import("./assets/pulse.svg")),
  PulseSolid: lazy(async () => import("./assets/pulse-solid.svg")),
  QuoteRight: lazy(async () => import("./assets/quote-right.svg")),
  Rainbow: lazy(async () => import("./assets/rainbow.svg")),
  Raindrops: lazy(async () => import("./assets/raindrops.svg")),
  RaindropsSolid: lazy(async () => import("./assets/raindrops-solid.svg")),
  Receipt: lazy(async () => import("./assets/receipt.svg")),
  ReceiptSolid: lazy(async () => import("./assets/receipt-solid.svg")),
  RecordVinyl: lazy(async () => import("./assets/record-vinyl.svg")),
  RecordVinylSolid: lazy(async () => import("./assets/record-vinyl-solid.svg")),
  RecSolid: lazy(async () => import("./assets/rec-solid.svg")),
  RectangleHorizontal: lazy(
    async () => import("./assets/rectangle-horizontal.svg")
  ),
  RectanglePanoramic: lazy(
    async () => import("./assets/rectangle-panoramic.svg")
  ),
  RectangleVertical: lazy(
    async () => import("./assets/rectangle-vertical.svg")
  ),
  Recycle: lazy(async () => import("./assets/recycle.svg")),
  Redo: lazy(async () => import("./assets/redo.svg")),
  RedoAlt: lazy(async () => import("./assets/redo-alt.svg")),
  RedoSolid: lazy(async () => import("./assets/redo-solid.svg")),
  Reflect: lazy(async () => import("./assets/reflect.svg")),
  ReflectSolid: lazy(async () => import("./assets/reflect-solid.svg")),
  Refresh: lazy(async () => import("./assets/refresh.svg")),
  Resize: lazy(async () => import("./assets/resize.svg")),
  ResizeSolid: lazy(async () => import("./assets/resize-solid.svg")),
  Resources: lazy(async () => import("./assets/resources.svg")),
  Rewind: lazy(async () => import("./assets/rewind.svg")),
  RewindSolid: lazy(async () => import("./assets/rewind-solid.svg")),
  Rhombus: lazy(async () => import("./assets/rhombus.svg")),
  RhombusSolid: lazy(async () => import("./assets/rhombus-solid.svg")),
  RingsWedding: lazy(async () => import("./assets/rings-wedding.svg")),
  Road: lazy(async () => import("./assets/road.svg")),
  RoadSolid: lazy(async () => import("./assets/road-solid.svg")),
  Rocket: lazy(async () => import("./assets/rocket.svg")),
  RocketSolid: lazy(async () => import("./assets/rocket-solid.svg")),
  RoomService: lazy(async () => import("./assets/room-service.svg")),
  RoomServiceSolid: lazy(async () => import("./assets/room-service-solid.svg")),
  RotateRight: lazy(async () => import("./assets/rotate-right.svg")),
  Rugby: lazy(async () => import("./assets/rugby.svg")),
  RugbySolid: lazy(async () => import("./assets/rugby-solid.svg")),
  Sad: lazy(async () => import("./assets/sad.svg")),
  SadSolid: lazy(async () => import("./assets/sad-solid.svg")),
  Salad: lazy(async () => import("./assets/salad.svg")),
  SaladSolid: lazy(async () => import("./assets/salad-solid.svg")),
  Scale: lazy(async () => import("./assets/scale.svg")),
  ScaleSolid: lazy(async () => import("./assets/scale-solid.svg")),
  School: lazy(async () => import("./assets/school.svg")),
  SchoolBus: lazy(async () => import("./assets/school-bus.svg")),
  SchoolBusSolid: lazy(async () => import("./assets/school-bus-solid.svg")),
  SchoolSolid: lazy(async () => import("./assets/school-solid.svg")),
  Scissors: lazy(async () => import("./assets/scissors.svg")),
  Screen: lazy(async () => import("./assets/screen.svg")),
  ScreenSolid: lazy(async () => import("./assets/screen-solid.svg")),
  Search: lazy(async () => import("./assets/search.svg")),
  SearchAlt: lazy(async () => import("./assets/search-alt.svg")),
  SearchAltSolid: lazy(async () => import("./assets/search-alt-solid.svg")),
  SearchHeart: lazy(async () => import("./assets/search-heart.svg")),
  SearchHeartSolid: lazy(async () => import("./assets/search-heart-solid.svg")),
  SearchSolid: lazy(async () => import("./assets/search-solid.svg")),
  Settings: lazy(async () => import("./assets/settings.svg")),
  SettingsSliders: lazy(async () => import("./assets/settings-sliders.svg")),
  SettingsSlidersSolid: lazy(
    async () => import("./assets/settings-sliders-solid.svg")
  ),
  SettingsSolid: lazy(async () => import("./assets/settings-solid.svg")),
  Share: lazy(async () => import("./assets/share.svg")),
  ShareSolid: lazy(async () => import("./assets/share-solid.svg")),
  Shield: lazy(async () => import("./assets/shield.svg")),
  ShieldCheck: lazy(async () => import("./assets/shield-check.svg")),
  ShieldCheckSolid: lazy(async () => import("./assets/shield-check-solid.svg")),
  ShieldExclamation: lazy(
    async () => import("./assets/shield-exclamation.svg")
  ),
  ShieldExclamationSolid: lazy(
    async () => import("./assets/shield-exclamation-solid.svg")
  ),
  ShieldInterrogation: lazy(
    async () => import("./assets/shield-interrogation.svg")
  ),
  ShieldInterrogationSolid: lazy(
    async () => import("./assets/shield-interrogation-solid.svg")
  ),
  ShieldPlus: lazy(async () => import("./assets/shield-plus.svg")),
  ShieldPlusSolid: lazy(async () => import("./assets/shield-plus-solid.svg")),
  ShieldSolid: lazy(async () => import("./assets/shield-solid.svg")),
  Ship: lazy(async () => import("./assets/ship.svg")),
  ShipSide: lazy(async () => import("./assets/ship-side.svg")),
  ShipSideSolid: lazy(async () => import("./assets/ship-side-solid.svg")),
  ShipSolid: lazy(async () => import("./assets/ship-solid.svg")),
  Shop: lazy(async () => import("./assets/shop.svg")),
  ShoppingBag: lazy(async () => import("./assets/shopping-bag.svg")),
  ShoppingBagAdd: lazy(async () => import("./assets/shopping-bag-add.svg")),
  ShoppingBagAddSolid: lazy(
    async () => import("./assets/shopping-bag-add-solid.svg")
  ),
  ShoppingBagSolid: lazy(async () => import("./assets/shopping-bag-solid.svg")),
  ShoppingCart: lazy(async () => import("./assets/shopping-cart.svg")),
  ShoppingCartAdd: lazy(async () => import("./assets/shopping-cart-add.svg")),
  ShoppingCartAddSolid: lazy(
    async () => import("./assets/shopping-cart-add-solid.svg")
  ),
  ShoppingCartCheck: lazy(
    async () => import("./assets/shopping-cart-check.svg")
  ),
  ShoppingCartCheckSolid: lazy(
    async () => import("./assets/shopping-cart-check-solid.svg")
  ),
  ShoppingCartSolid: lazy(
    async () => import("./assets/shopping-cart-solid.svg")
  ),
  ShopSolid: lazy(async () => import("./assets/shop-solid.svg")),
  Shuffle: lazy(async () => import("./assets/shuffle.svg")),
  ShuffleSolid: lazy(async () => import("./assets/shuffle-solid.svg")),
  SignalAlt: lazy(async () => import("./assets/signal-alt.svg")),
  SignalAlt1: lazy(async () => import("./assets/signal-alt-1.svg")),
  SignalAlt2: lazy(async () => import("./assets/signal-alt-2.svg")),
  SignIn: lazy(async () => import("./assets/sign-in.svg")),
  SignInAlt: lazy(async () => import("./assets/sign-in-alt.svg")),
  SignOut: lazy(async () => import("./assets/sign-out.svg")),
  SignOutAlt: lazy(async () => import("./assets/sign-out-alt.svg")),
  Skateboard: lazy(async () => import("./assets/skateboard.svg")),
  SkateboardSolid: lazy(async () => import("./assets/skateboard-solid.svg")),
  Smartphone: lazy(async () => import("./assets/smartphone.svg")),
  SmartphoneSolid: lazy(async () => import("./assets/smartphone-solid.svg")),
  Smile: lazy(async () => import("./assets/smile.svg")),
  SmileSolid: lazy(async () => import("./assets/smile-solid.svg")),
  SmileWink: lazy(async () => import("./assets/smile-wink.svg")),
  SmileWinkSolid: lazy(async () => import("./assets/smile-wink-solid.svg")),
  Snowflake: lazy(async () => import("./assets/snowflake.svg")),
  SnowflakeSolid: lazy(async () => import("./assets/snowflake-solid.svg")),
  Soap: lazy(async () => import("./assets/soap.svg")),
  SoapSolid: lazy(async () => import("./assets/soap-solid.svg")),
  Soup: lazy(async () => import("./assets/soup.svg")),
  SoupSolid: lazy(async () => import("./assets/soup-solid.svg")),
  Spa: lazy(async () => import("./assets/spa.svg")),
  SpaSolid: lazy(async () => import("./assets/spa-solid.svg")),
  Speaker: lazy(async () => import("./assets/speaker.svg")),
  SpeakerSolid: lazy(async () => import("./assets/speaker-solid.svg")),
  Sphere: lazy(async () => import("./assets/sphere.svg")),
  SphereSolid: lazy(async () => import("./assets/sphere-solid.svg")),
  Spinner: lazy(async () => import("./assets/spinner.svg")),
  SpinnerAlt: lazy(async () => import("./assets/spinner-alt.svg")),
  Square: lazy(async () => import("./assets/square.svg")),
  SquareRoot: lazy(async () => import("./assets/square-root.svg")),
  Star: lazy(async () => import("./assets/star.svg")),
  StarOctogram: lazy(async () => import("./assets/star-octogram.svg")),
  StarOctogramSolid: lazy(
    async () => import("./assets/star-octogram-solid.svg")
  ),
  StarSolid: lazy(async () => import("./assets/star-solid.svg")),
  Stats: lazy(async () => import("./assets/stats.svg")),
  Stethoscope: lazy(async () => import("./assets/stethoscope.svg")),
  Sticker: lazy(async () => import("./assets/sticker.svg")),
  StickerSolid: lazy(async () => import("./assets/sticker-solid.svg")),
  StopSolid: lazy(async () => import("./assets/stop-solid.svg")),
  Stopwatch: lazy(async () => import("./assets/stopwatch.svg")),
  StopwatchSolid: lazy(async () => import("./assets/stopwatch-solid.svg")),
  Subtitles: lazy(async () => import("./assets/subtitles.svg")),
  SubtitlesSolid: lazy(async () => import("./assets/subtitles-solid.svg")),
  Sun: lazy(async () => import("./assets/sun.svg")),
  Sunrise: lazy(async () => import("./assets/sunrise.svg")),
  SunriseSolid: lazy(async () => import("./assets/sunrise-solid.svg")),
  SunSolid: lazy(async () => import("./assets/sun-solid.svg")),
  Sword: lazy(async () => import("./assets/sword.svg")),
  SwordSolid: lazy(async () => import("./assets/sword-solid.svg")),
  Syringe: lazy(async () => import("./assets/syringe.svg")),
  SyringeSolid: lazy(async () => import("./assets/syringe-solid.svg")),
  Tablet: lazy(async () => import("./assets/tablet.svg")),
  TabletSolid: lazy(async () => import("./assets/tablet-solid.svg")),
  Target: lazy(async () => import("./assets/target.svg")),
  TargetSolid: lazy(async () => import("./assets/target-solid.svg")),
  Taxi: lazy(async () => import("./assets/taxi.svg")),
  TaxiSolid: lazy(async () => import("./assets/taxi-solid.svg")),
  Tennis: lazy(async () => import("./assets/tennis.svg")),
  TennisSolid: lazy(async () => import("./assets/tennis-solid.svg")),
  Terrace: lazy(async () => import("./assets/terrace.svg")),
  TerraceSolid: lazy(async () => import("./assets/terrace-solid.svg")),
  Test: lazy(async () => import("./assets/test.svg")),
  TestSolid: lazy(async () => import("./assets/test-solid.svg")),
  TestTube: lazy(async () => import("./assets/test-tube.svg")),
  TestTubeSolid: lazy(async () => import("./assets/test-tube-solid.svg")),
  Text: lazy(async () => import("./assets/text.svg")),
  TextCheck: lazy(async () => import("./assets/text-check.svg")),
  TextCheckSolid: lazy(async () => import("./assets/text-check-solid.svg")),
  TextSolid: lazy(async () => import("./assets/text-solid.svg")),
  ThermometerHalf: lazy(async () => import("./assets/thermometer-half.svg")),
  ThermometerHalfSolid: lazy(
    async () => import("./assets/thermometer-half-solid.svg")
  ),
  ThumbsDown: lazy(async () => import("./assets/thumbs-down.svg")),
  ThumbsDownSolid: lazy(async () => import("./assets/thumbs-down-solid.svg")),
  ThumbsUp: lazy(async () => import("./assets/thumbs-up.svg")),
  ThumbsUpSolid: lazy(async () => import("./assets/thumbs-up-solid.svg")),
  Thumbtack: lazy(async () => import("./assets/thumbtack.svg")),
  ThumbtackSolid: lazy(async () => import("./assets/thumbtack-solid.svg")),
  Ticket: lazy(async () => import("./assets/ticket.svg")),
  TicketSolid: lazy(async () => import("./assets/ticket-solid.svg")),
  TimeAdd: lazy(async () => import("./assets/time-add.svg")),
  TimeAddSolid: lazy(async () => import("./assets/time-add-solid.svg")),
  TimeCheck: lazy(async () => import("./assets/time-check.svg")),
  TimeDelete: lazy(async () => import("./assets/time-delete.svg")),
  TimeDeleteSolid: lazy(async () => import("./assets/time-delete-solid.svg")),
  TimeFast: lazy(async () => import("./assets/time-fast.svg")),
  TimeFastSolid: lazy(async () => import("./assets/time-fast-solid.svg")),
  TimeForward: lazy(async () => import("./assets/time-forward.svg")),
  TimeForwardSixty: lazy(async () => import("./assets/time-forward-sixty.svg")),
  TimeForwardTen: lazy(async () => import("./assets/time-forward-ten.svg")),
  TimeHalfPast: lazy(async () => import("./assets/time-half-past.svg")),
  TimeHalfPastSolid: lazy(
    async () => import("./assets/time-half-past-solid.svg")
  ),
  TimeOclock: lazy(async () => import("./assets/time-oclock.svg")),
  TimeOclockSolid: lazy(async () => import("./assets/time-oclock-solid.svg")),
  TimeQuarterPast: lazy(async () => import("./assets/time-quarter-past.svg")),
  TimeQuarterPastSolid: lazy(
    async () => import("./assets/time-quarter-past-solid.svg")
  ),
  TimeQuarterTo: lazy(async () => import("./assets/time-quarter-to.svg")),
  TimeQuarterToSolid: lazy(
    async () => import("./assets/time-quarter-to-solid.svg")
  ),
  TimeTwentyFour: lazy(async () => import("./assets/time-twenty-four.svg")),
  TimeTwentyFourSolid: lazy(
    async () => import("./assets/time-twenty-four-solid.svg")
  ),
  ToolCrop: lazy(async () => import("./assets/tool-crop.svg")),
  ToolMarquee: lazy(async () => import("./assets/tool-marquee.svg")),
  ToolMarqueeSolid: lazy(async () => import("./assets/tool-marquee-solid.svg")),
  Tooth: lazy(async () => import("./assets/tooth.svg")),
  ToothSolid: lazy(async () => import("./assets/tooth-solid.svg")),
  Tornado: lazy(async () => import("./assets/tornado.svg")),
  Transform: lazy(async () => import("./assets/transform.svg")),
  TransformSolid: lazy(async () => import("./assets/transform-solid.svg")),
  Trash: lazy(async () => import("./assets/trash.svg")),
  TrashSolid: lazy(async () => import("./assets/trash-solid.svg")),
  Treatment: lazy(async () => import("./assets/treatment.svg")),
  TreatmentSolid: lazy(async () => import("./assets/treatment-solid.svg")),
  Tree: lazy(async () => import("./assets/tree.svg")),
  TreeChristmas: lazy(async () => import("./assets/tree-christmas.svg")),
  TreeChristmasSolid: lazy(
    async () => import("./assets/tree-christmas-solid.svg")
  ),
  TreeSolid: lazy(async () => import("./assets/tree-solid.svg")),
  Triangle: lazy(async () => import("./assets/triangle.svg")),
  TriangleSolid: lazy(async () => import("./assets/triangle-solid.svg")),
  Trophy: lazy(async () => import("./assets/trophy.svg")),
  TrophySolid: lazy(async () => import("./assets/trophy-solid.svg")),
  TruckSide: lazy(async () => import("./assets/truck-side.svg")),
  TruckSideSolid: lazy(async () => import("./assets/truck-side-solid.svg")),
  Umbrella: lazy(async () => import("./assets/umbrella.svg")),
  UmbrellaSolid: lazy(async () => import("./assets/umbrella-solid.svg")),
  Underline: lazy(async () => import("./assets/underline.svg")),
  Undo: lazy(async () => import("./assets/undo.svg")),
  UndoAlt: lazy(async () => import("./assets/undo-alt.svg")),
  UndoSolid: lazy(async () => import("./assets/undo-solid.svg")),
  Unlock: lazy(async () => import("./assets/unlock.svg")),
  UnlockSolid: lazy(async () => import("./assets/unlock-solid.svg")),
  Upload: lazy(async () => import("./assets/upload.svg")),
  UsbPendrive: lazy(async () => import("./assets/usb-pendrive.svg")),
  UsbPendriveSolid: lazy(async () => import("./assets/usb-pendrive-solid.svg")),
  User: lazy(async () => import("./assets/user.svg")),
  UserAdd: lazy(async () => import("./assets/user-add.svg")),
  UserAddSolid: lazy(async () => import("./assets/user-add-solid.svg")),
  UserDelete: lazy(async () => import("./assets/user-delete.svg")),
  UserDeleteSolid: lazy(async () => import("./assets/user-delete-solid.svg")),
  UserRemove: lazy(async () => import("./assets/user-remove.svg")),
  UserRemoveSolid: lazy(async () => import("./assets/user-remove-solid.svg")),
  UserSolid: lazy(async () => import("./assets/user-solid.svg")),
  UserTime: lazy(async () => import("./assets/user-time.svg")),
  UserTimeSolid: lazy(async () => import("./assets/user-time-solid.svg")),
  Utensils: lazy(async () => import("./assets/utensils.svg")),
  UtensilsSolid: lazy(async () => import("./assets/utensils-solid.svg")),
  Vector: lazy(async () => import("./assets/vector.svg")),
  VectorAlt: lazy(async () => import("./assets/vector-alt.svg")),
  VectorAltSolid: lazy(async () => import("./assets/vector-alt-solid.svg")),
  VectorSolid: lazy(async () => import("./assets/vector-solid.svg")),
  Venus: lazy(async () => import("./assets/venus.svg")),
  VenusSolid: lazy(async () => import("./assets/venus-solid.svg")),
  Volleyball: lazy(async () => import("./assets/volleyball.svg")),
  VolleyballSolid: lazy(async () => import("./assets/volleyball-solid.svg")),
  Volume: lazy(async () => import("./assets/volume.svg")),
  VolumeSolid: lazy(async () => import("./assets/volume-solid.svg")),
  Wheelchair: lazy(async () => import("./assets/wheelchair.svg")),
  WheelchairSolid: lazy(async () => import("./assets/wheelchair-solid.svg")),
  WifiAlt: lazy(async () => import("./assets/wifi-alt.svg")),
  WifiAltSolid: lazy(async () => import("./assets/wifi-alt-solid.svg")),
  Wind: lazy(async () => import("./assets/wind.svg")),
  WomanHead: lazy(async () => import("./assets/woman-head.svg")),
  WomanHeadSolid: lazy(async () => import("./assets/woman-head-solid.svg")),
  World: lazy(async () => import("./assets/world.svg")),
  WorldSolid: lazy(async () => import("./assets/world-solid.svg")),
  Yen: lazy(async () => import("./assets/yen.svg")),
  ZoomIn: lazy(async () => import("./assets/zoom-in.svg")),
  ZoomInSolid: lazy(async () => import("./assets/zoom-in-solid.svg")),
  ZoomOut: lazy(async () => import("./assets/zoom-out.svg")),
  ZoomOutSolid: lazy(async () => import("./assets/zoom-out-solid.svg")),
};
